receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  opensearch:
    http:
      endpoint: ${OPENSEARCH_ENDPOINT}
      auth:
        authenticator: basicauth
    dataset: traces

extensions:
  basicauth:
    client_auth:
      username: ${OPENSEARCH_USERNAME}
      password: ${OPENSEARCH_PASSWORD}

service:
  extensions: [basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch]
